### ISSUE TITLE
website and documentation not syncronized?

### ISSUE THREAD

**Issue by frzifus** [skupperproject/skupper-docs#105]
I wonder if [skupper.io/docs](https://skupper.io/docs) is not syncronized with this repo since i can't find the [tutorial](https://skupper.io/docs/declarative/tutorial.html) section [here](https://github.com/skupperproject/skupper-docs/tree/main/modules/declarative/pages).

**Comment by pwright** [comment]
@frzifus as a temporary workaround, checkout https://skupper.netlify.app/

**Comment by pwright** [comment]
website is now synced,  specific section is at https://skupper.io/docs/declarative/index.html
