### ISSUE TITLE
Recommend podman users to update their network backend to netavark

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper-docs#181]
Podman documentation has a note saying that it is recommended for users to upgrade their
network backend from CNI to Netavark, as CNI is deprecated and will be removed in the future:
https://docs.podman.io/en/stable/markdown/podman-network.1.html

It seems useful to have a note in the podman sites documentation, recommending users to upgrade.

**Comment by ssorj** [comment]
Here's what I did on Fedora 38 to switch from CNI to Netaavark:

```
sudo dnf install netavark aardvark-dns
podman system reset (failed)
<fight with podman to list "external" containers and remove them>
podman system reset (succeeded)
```

The fighting part involved using `podman container ls --external` and `podman container rm <container-id>`.

And then I was good.
