### ISSUE TITLE
Document Headless Service support

### ISSUE THREAD

**Issue by LaumiH** [skupperproject/skupper-docs#32]
I've found no documentation for Skupper Headless Service support.

As there is quite a difference to ClusterIP Services, I'd love to include that in the documentation.

What do you think?

**Comment by pwright** [comment]
@LaumiH  currently, it's out of scope, but maybe this example would help? https://github.com/grs/skupper-example-cockroachdb

**Comment by pwright** [comment]
another example at https://github.com/skupperproject/skupper-example-kafka
